<?php
header('Content-Type: text/html; charset=utf-8');

$random_text = array(
	"<b>Fluttershy:</b> Um, my name is <i>[whispers]</i> Fluttershy...",
	"<b>Twilight Sparkle:</b> QUIET!<br><b>Pinkie Pie:</b> And then I said, \"Oatmeal, are you craz--\" oh.",
	"<b>Big McIntosh:</b> Eeyup.",
	"<b>Twilight Sparkle:</b> Scarf? Check. Saddle? Check. Boots? Check. Spike refusing to get up and going back to sleep? Check. It's a good thing I'm so organized. I'm ready!",
	"<b>Rainbow Dash:</b> The shape's fine, just make the whole thing you know, cooler. It needs to be about 20% cooler.",
	"<b>Pinkie Pie:</b> It's my tail! It's my tail! It's a-twitchin' twitchin'! And you know what that means...",
	"<b>Apple Bloom:</b> Oh wait, now I know how to call a chicken! Scootaloo! Scoot-Scootaloo!",
	"<b>Photo Finish:</b> Flüttershy, it is time to make... de magics!",
	"<b>Fluttershy:</b> I'm late! For a very important date!",
	"<b>Young Rarity:</b> A rock?! That's my destiny?! What is your problem, horn?! I followed you all the way out here for a rock?! <i>[grunts]</i> Dumb rock!",
	"<b>Owlowiscious:</b> Hooo.",
	"<b>Applejack:</b> \"Dressed\"? Uh, beg pardon Rarity, but, uh, we don't normally wear clothes.",
	"<b>Corrupted Fluttershy:</b> Your face! <i>[slams the bucket on Twilight Sparkle's head]</i>",
	"<i>[Discord tastes The Rainbow]</i>",
	"<b>Pinkie Pie:</b> Ba-kaw! Enough chit-chat! Time is candy!",
	"<b>Princess Luna:</b> But this is the traditional royal Canterlot voice! It is tradition to speak using the Royal \"we\", and to use <i>[louder and echoed]</i> THIS MUCH VOLUME WHEN ADDRESSING OUR SUBJECTS!",
	"<b>Rarity:</b> Uhh, let me guess: apple sauce?<br><b>Sweetie Belle:</b> Nope, toast!",
	"<b>Granny Smith:</b> Darn tootin'! It's time for some good old-fashioned Zap Apple Jammin'!",
	"<b>Derpy Hooves:</b> I just don't know what went wrong! <i>[gets electrocuted by the cloud]</i><br><b>Rainbow Dash:</b> <i>[sarcastically]</i> Yeah, it's a mystery.",
	"<b>Applejack:</b> Dear Princess Celestia; I wanted to share my thoughts with you. <i>[clears throat]</i> I didn't learn anythin'! Ha! I was right all along!",
	"<b>Sweetie Belle:</b> <i>[emerges from a bush]</i> Oh, come on!",
	"<b>Future Twilight Sparkle:</b> Twilight, please! I have a very important message for you from the future!",
	"<b>Princess Cadance:</b> <i>[about the bridesmaids' dresses]</i> And those should be a different color.<br><b>Twinkleshine:</b> I think they're lovely. <b>Minuette:</b> Me too! <b>Lyra Heartstrings:</b> I love them.",
	"<b>Shining Armor:</b> Twily!",
	"<b>Applejack:</b> Alrighty, ponies! Ready to have some fun?",
	"<b>Applejack:</b> Twilight...? Is that you?<br><i>[Twilight unveils her new wings to her friends with a white flash]</i>",
	"<b>Pinkie Pie:</b> Meh, suit yourself! <i>[kicks away the net, nest and party cannon]</i>",
	"<b>Pinkie Pie:</b> Most of my dreams are about frosting! <i><i>[licks her lips, giggles]</i></i>",
	"<b>Pinkie Pie:</b> Hey, you guys! Did you know I can totally play the organ? Because I didn't!",
	"<b>Rainbow Dash:</b> Yes, Ms. Harshwhinny. Y'know, 'professionalism' is my middle name. Rainbow Professionalism Dash.",
	"<b>Rarity:</b> Uh, Fluttershy, sweetness, please come down, and... do stop being a vampire bat. ",
	"<b>Twilight Sparkle:</b> Not counting the drama surrounding which of the bells from his cloak they've chosen to put on display! Spoiler alert: It's this one!",
	"<b>Cheese Sandwich</b>: Nopony calls me \"boneless\"! Right, Boneless?",
	"<b>Seabreeze:</b> <i>[tirade of indignation]</i><br><b>Applejack:</b> Uh... what did he say?",
	"<b>Maud Pie:</b> \"Rock, you are a rock. Gray, you are gray. Like a rock, which you are. Rock.\"<br>\"Rocks, these are my rocks. Sediments make me sentimental...\"",
	"<b>Rarity:</b> But, wait... I don't seem to need it anymore, do I? Yes. Yes! I can feel its magic flowing within me now! I'm so excited! I'm so excited!",
	"<b>Twilight Sparkle:</b> Equestria, We have a problem.",
	"<b>Rainbow Dash:</b> This just got real.",
	"<i>[Tirek tastes The Rainbow]</i>",
	"<b>Twilight Sparkle:</b> Let the rainbow remind that together we will always shine!",
	"<b>Sonata Dusk:</b> It's Taco Tuesday!!!",
	"<b>Starlight Glimmer:</b> In sameness, there is peace. Exceptionalism is a lie. Free yourself from your cutie mark. Choose equality as your special talent. Difference is frustration. To excel is to fail. Be your best by never being your best.",
	"<b>Twilight Sparkle:</b> Huh?! I'm pancake! I mean, awake...",
	"<b>Discord:</b> Knock knock! <i>[no one responds]</i> You're supposed to say 'Who's there?' This is the most basic of jokes! <i>[smashes a watermelon]</i><br><b>Maud Pie:</b> <i>[deadpan]</i> You're the most basic of jokes.",
	"<b>Octavia Melody:</b> <i>[gasps]</i> That's more like it!<br><i>[dubstep cello intensifies]</i>",
	"<b>Dr. Hooves:</b> I need this suit tailored! It's an emergency!",
	"<b>Spike:</b> <i>[sighs]</i> Princess life is good!",
	"<b>Spike:</b> Hmph! Princess Twilight will be rested, Princess Cadance will be proud, and Princess Spike deserves a little reward. Hah! Princess Spike.",
	"<b>Twilight Sparkle:</b> Okay, no problem. Just put the hay in the apple and eat the candle, hm?",
	"<b>Prince Rutherford:</b> Not perfect! Yaks destroy!",
	"<b>Pinkie Pie:</b> It's what I do when I'm not nervous! <i>[laughing hysterically]</i>",
	"<b>Fluttershy:</b> So, um, do we walk back up the slide or... or what?",
	"<b>Minuette:</b> Wait-wait-wait! Really fluff 'em up, huh? <i>[giggles]</i>",
	"<b>Pinkie Pie:</b> Are you kidding?! This is so exciting, I don't know how I'm ever going to— <i>[snores]</i>",
	"<b>Derpy:</b> <a href=\"http://i.imgur.com/eMRCr7k.jpg\"><i>[MEOW]</i></a>",
	"<b>Rainbow Dash:</b> <i>[embarrassed noise]</i> Coming!",
	"<b>Twilight Sparkle:</b> I'm bored.",
	"<b>Diamond Tiara:</b> A vote for Diamond Tiara is a vote for more Diamond Tiara!",
	"<b>Applejack:</b> Oh, sugarcube, if Mom and Dad were here, they'd be so proud of ya.",
	"<b>Mayor Mare:</b> <i>[hushed]</i> Speaking of secrets, have you ever known somepony else's secret?",
	"<b>Spike:</b> Just what I always wanted! A book.",
	"<b>Marble Pie:</b> Mm-hmm.<br><b>Big McIntosh:</b> Eeyup.",
	"<b>Maud Pie:</b> Have you ever wished you could turn into a rock?<br><b>Apple Bloom:</b> I had a dream once I was an apple.",
	"<b>Maud Pie:</b> <i>[deadpan]</i> The first one is about rocks. They're all about rocks.",
	"<b>Spike:</b> Whoa! That strange yellow orb in the sky! What is that?",
	"<b>Discord:</b> Eh... All you Apples look the same.",
	"<b>Big Daddy McColt:</b> If you ain't fer us, yer agin us.",
	"<b>Fluttershy:</b> Um, if you could just not yell so much, or maybe stop saying words altogether.",
	"<b>Spike:</b> And now she's coming back for revenge. Uh, or she was just really interested in your speech!",
	"<b>Starlight Glimmer:</b> Welcome home, Twilight!"
	);

echo $random_text[array_rand($random_text)];
